name: travel_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  ionicons: ^0.2.1
  form_builder_extra_fields: ^9.0.0
  http: ^0.13.6
  lottie: ^1.1.0
  hexcolor: ^2.0.4
  google_nav_bar: ^5.0.6
  auto_size_text: ^3.0.0
  flutter_native_splash: ^2.2.19
  provider: ^6.0.1
  share: ^2.0.4
  smooth_page_indicator: ^1.1.0
  get: ^4.6.5
  flutter_riverpod: ^2.3.4
  flutter_swiper: ^1.1.6
  flutter_svg: ^2.0.5
  panara_dialogs: ^0.1.4
  adaptive_dialog: ^1.8.3
  flutter_spinkit: ^5.1.0
  sqflite: ^2.0.0+3
  dialog: ^0.8.0
  api_cache_manager: ^1.0.1
  fluttertoast: ^8.2.1
  shimmer: ^2.0.0
  carousel_slider: ^4.0.0
  date_time_picker: ^2.0.0
  data_table_2: ^2.2.2
  intl: ^0.17.0
  shared_preferences: ^2.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/places/
    - assets/icons/
    - assets/
